struct ResVP
{
	float4 position:POSITION;
	float2 texCoord:TEXCOORD0;
};

ResVP main_plain_texture_vp(float4 position:POSITION, float2 texCoord0:TEXCOORD0, uniform float4x4 worldViewProj)
{
	ResVP result;

	result.position = mul(worldViewProj, position);
	result.texCoord = texCoord0;
	
	return result;
}

struct ResFP
{
	float4 color:COLOR;
};

ResFP main_plain_texture_fp(float2 uv0:TEXCOORD0, uniform sampler2D texture)
{
	ResFP result;
	result.color = tex2D(texture, uv0);
	return result;
}

