void main_plain_texture_vp(float4 position:POSITION, float2 texCoord0:TEXCOORD0, out float4 oPosition:POSITION, out float2 uv0:TEXCOORD0, uniform float4x4 worldViewProj)
{
	// Calculate output position
	oPosition = mul(worldViewProj, position);

	// Simply copy the input vertex UV to the output
	uv0 = texCoord0;
}

void main_plain_texture_fp(float2 uv0:TEXCOORD0, out float4 color:COLOR, uniform sampler2D texture)
{
	// Just sample texture using supplied UV
	color = tex2D(texture, uv0);
}